SELECT DISTINCT
    c.ITEM_ID,
    c.ITEM_NAME,
    c.RARITY
FROM 
    ITEM_INFO a
JOIN 
    ITEM_TREE b ON a.ITEM_ID = b.PARENT_ITEM_ID
JOIN 
    ITEM_INFO c ON b.ITEM_ID = c.ITEM_ID
WHERE 
    a.RARITY = 'RARE'
ORDER BY 
    c.ITEM_ID DESC;